-- # Generic Interrupt Interface
--
-- This interface assumes a typical interrupt handling flow is:
-- 1. Interrupt is triggered
-- 2. Interrupt is claimed, disabling the interrupt.
-- 3. Interrupt is marked as completed ("End Of Interrupt" / "EOI")
door Irq {
	-- Map an IRQ.
	--
	-- The interrupt is automatically claimed as soon as it occurs,
	-- disabling the interrupt until done is called.
	map = Map -> MapResult

	-- Unmap an IRQ.
	unmap = IrqNr -> Void

	-- Wait for an IRQ.
	--
	-- The IRQ will be masked after the call.
	-- It must be unmasked with `done()`.
	wait = IrqNr -> Void

	-- Mark an IRQ as completed.
	--
	-- This unmasks the interrupt.
	done = IrqNr -> Void
}

record Void {
}

-- An interrupt request ID
--
-- IRQs are device-specific.
--
-- It is expected that 4 billion IRQs shoul be sufficient for any usecase.
u32 IrqNr = 0 until 0xffff_ffff

u8 Level = 0
u8 Edge = 1
sum TriggerMode = Level | Edge

record Map {
	irq = IrqNr
	mode = TriggerMode
}

u8 Ok = 0
u8 Fail = 1
sum MapResult = Ok | Fail
